# Generated by Django 4.2.7 on 2026-01-18 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='metadata_raw',
            field=models.JSONField(blank=True, default=dict, help_text='All extracted metadata before cleaning', null=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='metadata_removed',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata fields that were removed', null=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='usermetadatapolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermetadatapolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, help_text='When the file was cleaned', null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was scanned'),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_fields', to='files.fileanalysis'),
        ),
        migrations.AlterField(
            model_name='usermetadatapolicy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['user', '-scanned_at'], name='files_filea_user_id_54f660_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatafield',
            index=models.Index(fields=['analysis', 'category'], name='files_metad_analysi_efb07a_idx'),
        ),
    ]
